In [1]:
import pandas as pd

In [2]:
nfdb = pd.read_csv("../data/NFDB_point.csv")
evac = pd.read_csv("../data/Canadian_Wildfire_Evacuation_Data.csv")

In [3]:
len(nfdb)

15206

In [4]:
len(evac)

1043

In [5]:
evac['FireSource'].head(2)

0    NFDB.poly
1    NFDB.poly
Name: FireSource, dtype: str

In [6]:
evac.columns

Index(['EvacID', 'Year', 'Province', 'Location', 'Lat', 'Long', 'Population',
       'PopulationNotes', 'FN_Reserve', 'EvacSize', 'IssueDate', 'EndDate',
       'EvacReason', 'Region', 'Group', 'FireSource', 'RepDOY', 'FireIgnit',
       'FireSize'],
      dtype='str')

In [7]:
evac.head(2)

,EvacID,Year,Province,Location,Lat,Long,Population,PopulationNotes,FN_Reserve,EvacSize,IssueDate,EndDate,EvacReason,Region,Group,FireSource,RepDOY,FireIgnit,FireSize
0,1,1980,MB,Clear Lake,50.678605,-99.911954,NaN,NaN,no,Very Small (1 to 100),5/23/1980,5/27/1980,Threat,SC,SC3,NFDB.poly,142.0,Human,22914.74086
1,2,1980,MB,Mafeking,52.683611,-101.110000,500,estimate (newspaper),no,"Small (101 to 1,000)",5/22/1980,5/28/1980,Threat,SC,SC2,NFDB.poly,139.0,Lightning,79934.29348

In [8]:
nfdb.head(2)

,FID,the_geom,NFDBFIREID,SRC_AGENCY,NAT_PARK,FIRE_ID,FIRENAME,LATITUDE,LONGITUDE,YEAR,MONTH,DAY,REP_DATE,OUT_DATE,SIZE_HA,CAUSE,FIRE_TYPE,RESPONSE,PROTZONE,MORE_INFO
0,NFDB_point.1,POINT (-1750186.0665132757 377790.0166569017),BC-2023-2023-K52813,BC,NaN,2023-K52813,UPPER PARK RILL C...,49.3014,-119.7091,2023,8,18,2023-08-18T00:00:00,2023-10-26T00:00:00,2043.8,H,Fire,FUL,NaN,Upper Park Rill Creek
1,NFDB_point.2,POINT (-1851062.9070163155 752606.0430763443),BC-2023-2023-C50100,BC,NaN,2023-C50100,DRIPPING WATER,52.0351,-123.1770,2023,4,27,2023-04-27T00:00:00,2023-05-29T00:00:00,209.0,H,Fire,FUL,NaN,E of Dripping Water Road

In [10]:
nfdb[(nfdb['SIZE_HA'] > 22914) & (nfdb['SIZE_HA'] < 22915)]

Empty DataFrame
Columns: [FID, the_geom, NFDBFIREID, SRC_AGENCY, NAT_PARK, FIRE_ID, FIRENAME, LATITUDE, LONGITUDE, YEAR, MONTH, DAY, REP_DATE, OUT_DATE, SIZE_HA, CAUSE, FIRE_TYPE, RESPONSE, PROTZONE, MORE_INFO]
Index: []